version: '3.6'
services:
  php:
    # image: 'php:7.2-fpm'
    build: 'php'
    volumes:
      - '.:/var/www/symfony:cached'
      - ./var/logs/symfony:/var/www/symfony/var/logs:cached
      - './conf/php.ini:/usr/local/etc/php/php.ini'
  nginx:
    image: 'nginx'
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www/symfony:cached'
      - './conf/default.conf:/etc/nginx/conf.d/default.conf'
  database:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ma_db
      - MYSQL_USER=mon_user
      - MYSQL_PASSWORD=secret!
  adminer:
    image: adminer
    ports:
      - '8081:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade
  composer:
    image: composer:latest
    volumes:
      - .:/app